// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAalPyz-poiEjRbhZPAQi12G-Vtf5JlIa0',
    appId: '1:433045774465:web:50a346d90fedc4eb44ed80',
    messagingSenderId: '433045774465',
    projectId: 'drivex-2a34e',
    authDomain: 'drivex-2a34e.firebaseapp.com',
    storageBucket: 'drivex-2a34e.firebasestorage.app',
    measurementId: 'G-LCC3MFLXNT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRJ7DGobw4KC9yonpfIQ_RzxNIEG0qjVI',
    appId: '1:433045774465:android:eb81b7ec63e31d1a44ed80',
    messagingSenderId: '433045774465',
    projectId: 'drivex-2a34e',
    storageBucket: 'drivex-2a34e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5I8rM0V2K6q5clPckN2ewBK7IieJxgOs',
    appId: '1:433045774465:ios:b54e184dd8044d1744ed80',
    messagingSenderId: '433045774465',
    projectId: 'drivex-2a34e',
    storageBucket: 'drivex-2a34e.firebasestorage.app',
    iosClientId: '433045774465-le2l7hikuokicee6bdh7h7vgqnq7fgni.apps.googleusercontent.com',
    iosBundleId: 'com.example.drivex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5I8rM0V2K6q5clPckN2ewBK7IieJxgOs',
    appId: '1:433045774465:ios:b54e184dd8044d1744ed80',
    messagingSenderId: '433045774465',
    projectId: 'drivex-2a34e',
    storageBucket: 'drivex-2a34e.firebasestorage.app',
    iosClientId: '433045774465-le2l7hikuokicee6bdh7h7vgqnq7fgni.apps.googleusercontent.com',
    iosBundleId: 'com.example.drivex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAalPyz-poiEjRbhZPAQi12G-Vtf5JlIa0',
    appId: '1:433045774465:web:78f98614aee30b8144ed80',
    messagingSenderId: '433045774465',
    projectId: 'drivex-2a34e',
    authDomain: 'drivex-2a34e.firebaseapp.com',
    storageBucket: 'drivex-2a34e.firebasestorage.app',
    measurementId: 'G-FLKS0E6010',
  );
}